# Generated by Django 3.2.8 on 2021-10-08 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('idUsuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('tipoDocumento', models.CharField(max_length=30)),
                ('numeroDocumento', models.BigIntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('fechaNacimiento', models.DateField()),
                ('telefono', models.BigIntegerField()),
                ('fotoPerfil', models.URLField()),
                ('administrador', models.BooleanField(default=False)),
                ('codigo', models.BigIntegerField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('idHorario', models.BigAutoField(primary_key=True, serialize=False)),
                ('diaInicio', models.CharField(max_length=10)),
                ('diaFin', models.CharField(max_length=10)),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('fechaCompra', models.DateTimeField()),
                ('fechaEntrega', models.DateTimeField()),
                ('total', models.IntegerField()),
                ('telefono', models.BigIntegerField()),
                ('nombreReceptor', models.CharField(max_length=70)),
                ('estado', models.CharField(max_length=30)),
                ('numeroArticulos', models.IntegerField()),
                ('observaciones', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=25)),
                ('precio', models.IntegerField()),
                ('cantidadDisponible', models.IntegerField(default=0)),
                ('descripcion', models.TextField()),
                ('marca', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('idUbicacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=60)),
                ('barrio', models.CharField(max_length=60)),
                ('numeroInmueble', models.IntegerField()),
                ('instruccionesAdicionales', models.TextField()),
                ('estado', models.CharField(max_length=60)),
                ('fechaActualizacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductoPedido',
            fields=[
                ('idProductoPedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productoPedidos', to='ferroticApp.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productoPedidos', to='ferroticApp.producto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='ferroticApp.ubicacion'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuarioComprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuarioVendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('idMensaje', models.BigAutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('fechaEnvio', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='ferroticApp.pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idComentario', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=25)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='ferroticApp.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('idArchivo', models.BigAutoField(primary_key=True, serialize=False)),
                ('archivo', models.CharField(max_length=200)),
                ('tipoContenido', models.CharField(max_length=80)),
                ('vistaPrevia', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='ferroticApp.producto')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='ferroticApp.ubicacion'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
