# Generated by Django 3.2.8 on 2021-10-15 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferroticApp', '0004_auto_20211009_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fechaCompra',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fechaEntrega',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nombreReceptor',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numeroArticulos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='observaciones',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='telefono',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='ferroticApp.ubicacion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidadDisponible',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='barrio',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='fechaActualizacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='instruccionesAdicionales',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='numeroInmueble',
            field=models.IntegerField(null=True),
        ),
    ]
