# Generated by Django 3.2.8 on 2021-10-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferroticApp', '0005_auto_20211015_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.DateField(null=True),
        ),
    ]
