# Generated by Django 3.2.8 on 2021-10-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferroticApp', '0006_alter_usuario_fechanacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='pedido',
            name='ciudad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
