from .usuarioDetailview import UsuarioDetailView
from .productoDetailView import ProductoDetailView
from .usuarioRegistroView import UsuarioRegistroView
from .productosBusqueda import ProductosBusqueda
from .usuarioLoginView import UsuarioLoginView
from .comprarView import ComprarView
from .productoUpdateView import ProductoUpdateView
from .productoDeleteView import ProductoDeleteView
from .pedidoUpdateView import PedidoUpdateView
from .crearProductosView import CrearProductosView
from .crearPedidoView import CrearPedidoView
from .pedidoDetalleView import PedidoDetalleView
from .crearProductoPedidoView import CrearProductoPedidoView
from .productoPedidoRUDView import ProductoPedidoRUDView
